// client-old/src/components/SessionSelect.vue
<script setup lang="ts">
import type { Id } from '@/types/id';
import { Session } from '@/types/job';
import API from '@/utils/api';
import { onMounted, shallowRef } from 'vue';
import cookies from '@/utils/cookies';

const SESSION_KEY = 'session';

const props = defineProps<{
    categoryId: Id;
}>();

const sessions = shallowRef<Session[]>([]);
const selected = shallowRef<Session>();

onMounted(async () => {
    const sessionsResult = await API.jobs.getAllSessionsInCategory({ categoryId: props.categoryId });
    if (!sessionsResult.status) {
        // TODO handle error
        return;
    }

    sessions.value = sessionsResult.data.map(Session.fromServer).sort((a, b) => +a.createdAt - +b.createdAt);
    const cookieId = cookies.get(SESSION_KEY);

    const sessionFromCookie = sessions.value.find(s => s.id === cookieId);
    if (sessionFromCookie) {
        selected.value = sessionFromCookie;
        return;
    }

    selected.value = sessions.value[0];
    cookies.set(SESSION_KEY, selected.value.id);
});

function input(event: Event) {
    if (!sessions.value)
        return;

    const id = (event.target as unknown as { value?: string })?.value;
    const newSession = sessions.value.find(s => s.id === id);
    if (!newSession)
        return;

    selected.value = newSession;
    cookies.set(SESSION_KEY, selected.value.id);
}


async function createSession() {
    const result = await API.jobs.createSession({ categoryId: props.categoryId });
    if (!result.status) {
        // TODO handle error
        return;
    }

    const session = Session.fromServer(result.data);
    sessions.value = [ session, ...sessions.value ];
    selected.value = session;
    cookies.set(SESSION_KEY, selected.value.id);
}
</script>

<template>
    <div class="d-flex align-items-center gap-3">
        <div>
            <span class="fw-semibold me-2">Session:</span>
            <select
                class="reset-select"
                :value="selected?.id"
                @input="input"
            >
                <option
                    v-for="session in sessions"
                    :key="session.id"
                    :value="session.id"
                >
                    {{ session.id }}
                </option>
            </select>
        </div>
        <div>
            <span class="fw-semibold me-2">Since:</span>
            <span>{{ selected?.createdAt.toISOString() }}</span>
        </div>
        <button
            @click="createSession"
        >
            New session
        </button>
    </div>
</template>

<style scoped>
.reset-select {
    color: inherit;
    outline: none;
    background-color: transparent;
    border: none;
    padding: 0;
    margin: 0;
    font: inherit;
    cursor: pointer;
}

.reset-select option {
    background-color: var(--color-background);
}
</style>

// client/src/components/context/SessionSelect.tsx
import { api } from '@/api';
import { type Id } from '@/types/id';
import { Session } from '@/types/job';
import { cookies } from '@/types/utils/cookies';
import { Button, Select, SelectItem, type SharedSelection } from '@heroui/react';
import { useCallback, useEffect, useState } from 'react';
import { useCategoryInfo } from './CategoryInfoProvider';

const SESSION_COOKIE_NAME = 'session';

/**
 * Dropdown to to select a session, and button to create a new session, for a schema category.
 */
// The functionality should be partially moved to Backend in the future.
export function SessionSelect() {
    const categoryId = useCategoryInfo().category.id;
    const [ sessions, setSessions ] = useState<Session[]>([]);
    const [ selected, setSelected ] = useState<Session>();

    const fetchSessions = useCallback(async (categoryId: Id) => {
        const response = await api.jobs.getAllSessionsInCategory({ categoryId });
        if (!response.status) {
            // TODO handle error
            return;
        }

        const fetchedSession = response.data.map(Session.fromResponse).sort((a, b) => +a.createdAt - +b.createdAt);
        setSessions(fetchedSession);

        const cookieId = cookies.get(SESSION_COOKIE_NAME);

        const sessionFromCookie = fetchedSession.find(s => s.id === cookieId);
        if (sessionFromCookie) {
            setSelected(sessionFromCookie);
            return;
        }

        const defaultSession = fetchedSession[0];
        setSelected(defaultSession);
        cookies.set(SESSION_COOKIE_NAME, defaultSession.id);
    }, []);

    useEffect(() => {
        void fetchSessions(categoryId);
    }, [ categoryId, fetchSessions ]);

    async function createSession() {
        const result = await api.jobs.createSession({ categoryId });
        if (!result.status) {
            // TODO handle error
            return;
        }

        const session = Session.fromResponse(result.data);
        setSessions([ session, ...sessions ]);
        setSelected(session);
        cookies.set(SESSION_COOKIE_NAME, session.id);
    }

    const selectSession = useCallback((keys: SharedSelection) => {
        if (!sessions)
            return;

        const id = (keys as Set<Id>).values().next().value!;
        const newSession = sessions.find(s => s.id === id);
        if (!newSession)
            return;

        setSelected(newSession);
        cookies.set(SESSION_COOKIE_NAME, id);
    }, [ sessions ]);

    return (
        // Hidden visibility, the session is needed for the app to work,
        // but for now the user does not need it.
        <div className='h-12 items-center gap-3 invisible'>
            <Select
                label='Session'
                defaultSelectedKeys={selected ? [ selected.id ] : []}
                onSelectionChange={selectSession}
                disallowEmptySelection
                size='sm'
                className='w-[320px]'
            >
                {sessions.map(session => (
                    <SelectItem key={session.id}>
                        {session.id}
                    </SelectItem>
                ))}
            </Select>
            <Button onPress={createSession}>
                New session
            </Button>
        </div>
    );
}
